#!/bin/bash

# Programs
PYTHON="python3"              # Python version installed (3 or above)

# Files
SCRIPTS_DIR="../scripts/"     # The directory for scripts
SAVE="../data/fractions.txt"  # File contaiining Voronoi polyhedra data
PARENT="jianqi_data"          # The parent directory name
DICT="[300, 800, 1300]"       # List of temperatures to examine

# Copy trajectory data from VASP runs
${PYTHON} ${SCRIPTS_DIR}vp_group.py\
	"-s${SAVE}"\
	"-p${PARENT}"\
	"-d${DICT}"\
