#!/bin/bash

# Programs
PYTHON="python3"              # Python version installed (3 or above)

# Files
SCRIPTS_DIR="../scripts/"     # The directory for scripts
TRAJ_NAME="XDATCAR"           # The name of the type of file containing trajectories
DATA="../data/"               # Directory were data is stored
SAVE="../data/fractions.txt"  # File to save fraction data

# Analysis variables
EDGES="5"                     # The Voronoi polyhedra edge index
FACES="8"                     # The Voronoi polyhedra minimum number of faces
THRESHOLD="0.0"               # The minimum edge length for a Voronoi polyhedra

# Copy trajectory data from VASP runs
${PYTHON} ${SCRIPTS_DIR}vp_individual.py\
	"-n${TRAJ_NAME}"\
	"-d${DATA}"\
	"-e${EDGES}"\
	"-f${FACES}"\
	"-t${THRESHOLD}"\
	"-s${SAVE}"\
